set nocompatible      " Nécessaire
filetype off          " Nécessaire

" Ajout de Vundle au runtime path et initialisation
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" On indique à Vundle de s'auto-gérer
Plugin 'gmarik/Vundle.vim'  " Nécessaire
"""""""""""""""""""""""""""""""""""
" Liste des plugins que Vundle doit gérer
"""""""""""""""""""""""""""""""""""
Plugin 'scrooloose/nerdtree'
Plugin 'alvan/vim-closetag'
Plugin 'justinmk/vim-sneak'
Plugin 'joshdick/onedark.vim'
Plugin 'LukeGoodsell/nextflow-vim'
Plugin 'sheerun/vim-polyglot'
Plugin 'itchyny/lightline.vim'
Plugin 'https://github.com/snakemake/snakemake.git', {'rtp': 'misc/vim/'}
Plugin 'mhinz/vim-startify'
call vundle#end()            " Nécessaire
filetype plugin indent on    " Nécessaire

"""""""""""""""""""""""""""""""""""
" Reste du .vimrc
"""""""""""""""""""""""""""""""""""
hi! Sneak guifg=white guibg=red ctermfg=black ctermbg=LightBlue
hi! SneakScope guifg=red guibg=yellow ctermfg=LightMagenta ctermbg=Magenta
hi! SneakLabel guifg=white guibg=magenta ctermfg=black ctermbg=LightGreen
"Generalites
set mouse=a
set noswapfile
set number
syntax on
set cursorline
set noerrorbells
set novisualbell
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set backspace=indent,eol,start "Permet d'utiliser la touche effacer sur mac
let g:sneak#label = 1
highlight ColorColumn guibg=grey ctermbg=16
set colorcolumn=80
autocmd InsertEnter,InsertLeave * set cul!
set noshowmode


"Thème utilisé
set laststatus=2
let g:lightline = {
  \ 'colorscheme': 'onedark',
  \ }
if (has("autocmd") && !has("gui_running"))
  augroup colorset
    autocmd!
    let s:white = { "gui": "#ABB2BF", "cterm": "145", "cterm16" : "7" }
    autocmd ColorScheme * call onedark#set_highlight("Normal", { "fg": s:white }) " `bg` will not be styled since there is no `bg` setting
  augroup END
endif
colorscheme onedark

"Shortcuts
"<CR> is the same as click on the button Enter
"nnoremap : only available in normal mode
autocmd Filetype python nnoremap <buffer> <F5> :w<CR>:!clear && python %<CR>
autocmd Filetype r nnoremap <buffer> <F5> :w<CR>:!clear && Rscript %<CR>
autocmd Filetype tex nnoremap <buffer> <F5> :w<CR>:!clear && pdflatex %<CR>
autocmd Filetype c nnoremap <buffer> <F5> :w<CR>:!clang % -o %:r && clear && ./%:r<CR>

autocmd FileType html setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType css setlocal shiftwidth=2 tabstop=2 softtabstop=2

nmap <F6> :NERDTreeToggle<CR>
au VimEnter *  NERDTree
autocmd VimEnter * wincmd p
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
let NERDTreeMinimalUI=1


let s:header = [
    \ '   __      _______ __  __ ',
    \ '   \ \    / /_   _|  \/  |',
    \ '    \ \  / /  | | | \  / |',
    \ '     \ \/ /   | | | |\/| |',
    \ '      \  /   _| |_| |  | |',
    \ '       \/   |_____|_|  |_|',
    \ '',
    \ ]
let g:startify_custom_header = s:header
