local wk = require("which-key")

wk.register({
	t = { "<cmd>TestFile<cr>", "Test file" },
	T = { "<cmd>TestSuite<cr>", "Test workspace" },
	h = { "<C-W>s<cr>", "split below" },
	v = { "<C-W>v<cr>", "split right" },
	s = { "<cmd>w<cr>", "save" },
	e = { "<cmd>Explore<cr>", "Netrw" },
	n = { "<cmd>lnext<cr>", "Next in localfix" },
	p = { "<cmd>lprev<cr>", "Prev in localfix" },
	w = { "<cmd>bdelete<cr>", "Close buffer" },
	b = { "<cmd>b#<cr>", "Switch back to last buffer" },
	r = { "<cmd>TREPLSendRegion<CR>", "Run Tressitter Node" },
	o = { "<cmd>call ToggleWindowLayout()<cr>", "Switch window layout" },
	d = {
		name = "+Diagnostic",
		n = { "<cmd>lua vim.diagnostic.goto_next()<cr>", "Next diagnostic" },
		p = { "<cmd>lua vim.diagnostic.goto_prev()<cr>", "Prev diagnostic" },
		l = { "<cmd>lua vim.diagnostic.open_float()<cr>", "Line diagnostics" },
		d = { "<cmd>lua require('telescope.builtin').diagnostics({bufnr=0})<cr>", "Document diagnostics" },
	},
	f = {
		name = "+Telescope",
		p = { "<cmd>lua require('telescope.builtin').oldfiles()<cr>", "Previous open files" },
		f = { "<cmd>lua require('telescope.builtin').find_files()<cr>", "Files" },
		h = { "<cmd>lua require('telescope.builtin').command_history()<cr>", "History" },
		o = { "<cmd>lua require('telescope.builtin').vim_options()<cr>", "vim_options" },
		g = { "<cmd>lua require('telescope.builtin').live_grep()<cr>", "Text" },
		t = { "<cmd>lua require('telescope.builtin').treesitter()<cr>", "Treesitter" },
		s = { "<cmd>lua require('telescope.builtin').lsp_document_symbols()<cr>", "Symbols" },
		r = { "<cmd>lua require('telescope.builtin').registers()<cr>", "Registers" },
		b = { "<cmd>lua require('telescope.builtin').buffers()<cr>", "buf_fuz_find" },
	},
	g = {
		name = "+Git",
		o = { "<cmd>Neogit<CR>", "Open Neogit" },
		b = { "<cmd>lua require'telescope.builtin'.git_branches()<cr>", "git branches" },
	},
	l = {
		name = "+LSP",
		g = { "<cmd>lua vim.lsp.buf.definition()<cr>", "Go to definition" },
		t = { "<cmd>lua vim.lsp.buf.type_definition()<cr>", "Type definition" },
		r = { "<cmd>lua vim.lsp.buf.rename()<cr>", "Rename symbol" },
		h = { "<cmd>lua vim.lsp.buf.hover()<cr>", "Hover" },
		a = { "<cmd>lua require('telescope.builtin').lsp_code_actions()<cr>", "Code actions" },
		R = { "<cmd>lua require('telescope.builtin').lsp_references()<cr>", "Symbol References" },
		D = { "<cmd>lua require('telescope.builtin').lsp_workspace_diagnostics()<cr>", "Workspace diagnostics" },
		s = { "<cmd>lua require('telescope.builtin').lsp_document_symbols()<cr>", "Document symbols" },
		S = { "<cmd>lua require('telescope.builtin').lsp_workspace_symbols()<cr>", "Workspace symbols" },
	},
}, {
	prefix = "<leader>",
})
