local wk = require("which-key")

wk.register({
	c = { "comment toggle" },
	h = { "<C-W>s<cr>", "split below" },
	v = { "<C-W>v<cr>", "split right" },
	s = { "<cmd>w<cr>", "save" },
	n = { "<cmd>lnext<cr>", "Next in localfix" },
	p = { "<cmd>lprev<cr>", "Prev in localfix" },
	w = { "<cmd>bdelete<cr>", "Close buffer" },
	b = { "<cmd>Telescope buffers<cr>", "list open buffers" },
	f = {
		name = "+Telescope",
		p = { "<cmd>Telescope projects<cr>", "Previous projects" },
		P = { "<cmd>Telescope oldfiles<cr>", "Previous open files" },
		f = { "<cmd>Telescope find_files<cr>", "Files" },
		h = { "<cmd>Telescope command_history<cr>", "History" },
		o = { "<cmd>Telescope vim_options<cr>", "vim_options" },
		g = { "<cmd>Telescope live_grep<cr>", "Text" },
		r = { "<cmd>Telescope registers<cr>", "Registers" },
		b = { "<cmd>Telescope buffers<cr>", "buf_fuz_find" },
	},
	g = {
		name = "+Git",
		o = { "<cmd>Neogit<CR>", "Open Neogit" },
		b = { "<cmd>Telescope git_branches<cr>", "git branches" },
	},
	l = {
		name = "+LSP",
		a = { "<cmd>Telescope lsp_code_actions theme=get_cursor<cr>", "Code action" },
		g = { "<cmd>lua vim.lsp.buf.definition()<cr>", "Go to definition" },
		t = { "<cmd>lua vim.lsp.buf.type_definition()<cr>", "Type definition" },
		r = { "<cmd>Telescope lsp_references layout_strategy=vertical<cr>", "Symbol References" },
		R = { "<cmd>lua vim.lsp.buf.rename()<cr>", "Rename symbol" },
		d = { "<cmd>lua vim.lsp.diagnostic.set_loclist()<cr>", "Document diagnostics" },
		D = { "<cmd>Telescope lsp_workspace_diagnostics<cr>", "Workspace diagnostics" },
		s = { "<cmd>Telescope lsp_document_symbols<cr>", "Document symbols" },
		S = { "<cmd>Telescope lsp_workspace_symbols<cr>", "Workspace symbols" },
		n = { "<cmd>lua vim.lsp.diagnostic.goto_next()<cr>", "Next diagnostic" },
		p = { "<cmd>lua vim.lsp.diagnostic.goto_prev()<cr>", "Prev diagnostic" },
		h = { "<cmd>lua vim.lsp.buf.hover()<cr>", "Hover" },
	},
}, {
	prefix = "<leader>",
})
